name: TPeH
main: com.imdeity.tpeh.TPeH
version: 1.1
language: english.yml
author: vanZeben
website: http://imdeity.com/
softdepend: [DeityAPI]
commands:
    teleportaccept:
        aliases: [tpa]
    teleportaccepthere:
        aliases: [tpah]